# Generated by Django 5.2.6 on 2025-09-10 08:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Sites Map', max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_text_en', models.CharField(blank=True, default='', max_length=300)),
                ('footer_text_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('logo_left_en', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_left_ar', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_right_en', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_right_ar', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('header_bg', models.CharField(default='#02466b', max_length=20)),
                ('footer_bg', models.CharField(default='#02466b', max_length=20)),
                ('default_center_lat', models.FloatField(default=23.8859)),
                ('default_center_lon', models.FloatField(default=45.0792)),
                ('default_zoom', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)])),
                ('show_filter_region', models.BooleanField(default=True)),
                ('show_filter_governorate', models.BooleanField(default=True)),
                ('show_filter_crop_type', models.BooleanField(default=True)),
                ('show_filter_water_source', models.BooleanField(default=True)),
                ('show_filter_irrigation_type', models.BooleanField(default=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='machine key (e.g. energy_source)', unique=True)),
                ('label_en', models.CharField(max_length=200)),
                ('label_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choice')], default='text', max_length=10)),
                ('is_filterable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('farmer_name', models.CharField(blank=True, default='', max_length=200)),
                ('farmer_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('region_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('governorate', models.CharField(blank=True, default='', max_length=200)),
                ('governorate_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('crop_type', models.CharField(blank=True, default='', max_length=200)),
                ('crop_type_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('water_source', models.CharField(blank=True, default='', max_length=200)),
                ('water_source_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('irrigation_system_type', models.CharField(blank=True, default='', max_length=200)),
                ('irrigation_system_type_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('distribution_uniformity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('number_of_trees', models.PositiveIntegerField(blank=True, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('design_pdf', models.FileField(blank=True, null=True, upload_to='designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.site')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('url_template', models.URLField(help_text='Leaflet tile URL template, e.g. https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png')),
                ('is_default', models.BooleanField(default=False)),
                ('min_zoom', models.PositiveSmallIntegerField(default=0)),
                ('max_zoom', models.PositiveSmallIntegerField(default=19)),
                ('attribution', models.CharField(blank=True, default='', max_length=300)),
                ('subdomains', models.CharField(blank=True, default='', help_text="e.g. 'abc'", max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='app.appsettings')),
            ],
            options={
                'unique_together': {('settings', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SiteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_en', models.CharField(blank=True, default='', max_length=500)),
                ('value_ar', models.CharField(blank=True, max_length=500, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customfield')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='app.site')),
            ],
            options={
                'unique_together': {('site', 'field')},
            },
        ),
    ]
