# Generated by Django 5.2.6 on 2025-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='logo_left_ar',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='logo_left_en',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='logo_right_ar',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='logo_right_en',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='name_ar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='name_en',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='subdomains',
            field=models.CharField(blank=True, default='', help_text="e.g. 'abc' or 'abcd'", max_length=50),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='url_template',
            field=models.CharField(help_text='Leaflet tile URL template, e.g. https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', max_length=512),
        ),
    ]
