# Generated by Django 5.2.6 on 2025-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appsettings_favicon_alter_appsettings_logo_left_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='number_of_trees',
            field=models.CharField(blank=True, help_text='Accepts numbers or free text, e.g., One Greenhouse', max_length=120, null=True),
        ),
    ]
