# Generated by Django 5.2.6 on 2025-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_site_number_of_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='show_filter_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_filter_trees',
            field=models.BooleanField(default=True),
        ),
    ]
